import typescript from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import replace from "@rollup/plugin-replace";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const pkg = require("./package.json");

const isProd = process.env.BUILD === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
	input: "src/main.ts",
	output: {
		dir: ".",
		sourcemap: "inline",
		sourcemapExcludeSources: isProd,
		format: "cjs",
		exports: "default",
		banner,
	},
	external: ["obsidian"],
	plugins: [
		replace({
			preventAssignment: true,
			__VERSION__: JSON.stringify(pkg.version),
		}),
		typescript(),
		nodeResolve({ browser: true }),
		commonjs(),
	],
};
